services:

  splent_feature_redis:
    image: redis:7.4
    restart: always
    ports:
      - "${REDIS_HOST_PORT}:6379"
    networks:
      - splent_network

networks:
  splent_network:
    external: true